#!/usr/bin/env python3
"""
Test runner for SANDBOX_COUNT AST operations count tests.

This script:
1. Runs all test cases and compares generated bytecode with expected outputs
2. Verifies that bytecode extraction is deterministic (same result every time)
3. Generates expected outputs if they don't exist (--generate flag)
4. Reports test results in a structured format

Usage:
    python test_runner.py                      # Run all tests
    python test_runner.py --generate           # Generate expected outputs
    python test_runner.py --list               # List all test cases
    python test_runner.py <test_file>          # Run specific test
    python test_runner.py --deterministic-check # Test bytecode extraction determinism
"""

import sys
import os
import argparse
import json
from pathlib import Path
from bytecode_extract import extract_bytecode, format_bytecode, get_total_operations_count, compare_bytecode

# PyCF_SANDBOX_COUNT flag value (must match Include/cpython/compile.h)
PyCF_SANDBOX_COUNT = 0x8000

# Test directories
TEST_BASE_DIR = Path(__file__).parent / "testcases"
TEST_CATEGORIES = ["simple", "medium", "complex"]


def discover_tests():
    """Discover all test cases organized by category."""
    tests = {}
    for category in TEST_CATEGORIES:
        category_dir = TEST_BASE_DIR / category
        if category_dir.exists():
            tests[category] = sorted(category_dir.glob("*.py"))
    return tests


def load_expected(test_file):
    """Load expected bytecode output for a test file."""
    expected_file = test_file.with_suffix('.expected')
    if expected_file.exists():
        return expected_file.read_text().strip()
    return None


def save_expected(test_file, bytecode):
    """Save expected bytecode output for a test file."""
    expected_file = test_file.with_suffix('.expected')
    expected_file.write_text(bytecode)
    return expected_file


def run_test(test_file, generate=False):
    """
    Run a single test case.
    
    Returns:
        (passed, message, total_ops)
    """
    source = test_file.read_text()
    
    # Extract bytecode
    ops = extract_bytecode(source, str(test_file))
    bytecode = format_bytecode(ops)
    total_ops = get_total_operations_count(ops)
    
    if generate:
        # Generate expected output
        expected_file = save_expected(test_file, bytecode)
        return True, f"Generated expected output: {expected_file}", total_ops
    
    # Compare with expected
    expected = load_expected(test_file)
    if expected is None:
        return False, f"No expected output found (run with --generate)", total_ops
    
    # Parse expected bytecode
    # Expected format: "offset: L<line> OPNAME arg" or "offset:      OPNAME arg"
    expected_ops = []
    for line in expected.strip().split('\n'):
        if line.startswith('Total operations count:'):
            continue
        if not line.strip():
            continue
        # Parse "offset: L<line> OPNAME arg" or "offset:      OPNAME arg"
        parts = line.split()
        if len(parts) >= 2:
            offset = int(parts[0].rstrip(':'))
            # Check if parts[1] == 'L' (line info marker)
            if parts[1] == 'L':
                # Format: offset: L <line> OPNAME arg
                if len(parts) >= 4:
                    # parts[2] is line number, parts[3] is opname
                    opname = parts[3]
                    arg = int(parts[4]) if len(parts) > 4 else None
                else:
                    continue
            else:
                # Format: offset: OPNAME arg (backward compat)
                opname = parts[1]
                arg = int(parts[2]) if len(parts) > 2 else None
            # Create OpcodeInfo without position info for comparison
            from bytecode_extract import OpcodeInfo
            expected_ops.append(OpcodeInfo(offset, opname, arg, None, None, None))
    
    is_equal, message = compare_bytecode(expected_ops, ops)
    
    return is_equal, message, total_ops


def test_deterministic(test_file):
    """
    Test that bytecode extraction is deterministic (same result every time).
    
    Returns:
        (consistent, message, total_ops1, total_ops2)
    """
    source = test_file.read_text()
    
    # Extract bytecode twice
    ops1 = extract_bytecode(source, str(test_file))
    total_ops1 = get_total_operations_count(ops1)
    
    ops2 = extract_bytecode(source, str(test_file))
    total_ops2 = get_total_operations_count(ops2)
    
    # Should be exactly the same
    is_consistent = total_ops1 == total_ops2
    
    if is_consistent:
        message = f"Deterministic: {total_ops1} operations (consistent across runs)"
    else:
        message = f"Non-deterministic: {total_ops1} vs {total_ops2} - WARNING!"
    
    return is_consistent, message, total_ops1, total_ops2


def run_all_tests(generate=False, deterministic_check=False):
    """Run all discovered tests."""
    tests = discover_tests()
    
    results = {
        'passed': 0,
        'failed': 0,
        'generated': 0,
        'deterministic': 0,
        'non_deterministic': 0,
        'details': []
    }
    
    print(f"\n{'='*70}")
    print("SANDBOX_COUNT AST Operations Count Tests")
    print(f"{'='*70}\n")
    
    for category in TEST_CATEGORIES:
        if category not in tests or not tests[category]:
            continue
        
        print(f"\n{category.upper()} TESTS:")
        print("-" * 70)
        
        for test_file in tests[category]:
            test_name = test_file.name
            
            if generate:
                passed, message, total_ops = run_test(test_file, generate=True)
                results['generated'] += 1
                print(f"  [GEN] {test_name:<40} {message}")
            elif deterministic_check:
                consistent, message, total_ops1, total_ops2 = test_deterministic(test_file)
                if consistent:
                    results['deterministic'] += 1
                    status = "[OK]"
                else:
                    results['non_deterministic'] += 1
                    status = "[DIFF]"
                print(f"  {status} {test_name:<40} {message}")
            else:
                passed, message, total_ops = run_test(test_file, generate=False)
                if passed:
                    results['passed'] += 1
                    status = "[PASS]"
                else:
                    results['failed'] += 1
                    status = "[FAIL]"
                print(f"  {status} {test_name:<40} ops={total_ops}")
                if not passed:
                    print(f"       -> {message}")
    
    # Print summary
    print(f"\n{'='*70}")
    print("SUMMARY:")
    print(f"{'='*70}")
    
    if generate:
        print(f"Generated {results['generated']} expected output files")
    elif deterministic_check:
        print(f"Deterministic: {results['deterministic']}")
        print(f"Non-deterministic: {results['non_deterministic']}")
        print(f"\nNote: Non-deterministic results indicate a bug in bytecode extraction")
    else:
        print(f"Passed: {results['passed']}")
        print(f"Failed: {results['failed']}")
        print(f"Total:  {results['passed'] + results['failed']}")

    return results['failed'] == 0 if not generate and not deterministic_check else True


def list_tests():
    """List all available test cases."""
    tests = discover_tests()
    
    print("\nAvailable Test Cases:")
    print("=" * 70)
    
    for category in TEST_CATEGORIES:
        if category not in tests or not tests[category]:
            continue
        
        print(f"\n{category.upper()}:")
        for test_file in tests[category]:
            # Read first comment line for description
            lines = test_file.read_text().split('\n')
            desc = ""
            for line in lines:
                if line.startswith('#'):
                    desc = line.lstrip('#').strip()
                    break
            print(f"  {test_file.name:<40} {desc[:30]}")


def main():
    parser = argparse.ArgumentParser(
        description="Test runner for SANDBOX_COUNT AST operations count"
    )
    parser.add_argument('--generate', action='store_true',
                        help='Generate expected output files')
    parser.add_argument('--list', action='store_true',
                        help='List all test cases')
    parser.add_argument('--deterministic-check', action='store_true',
                        help='Test bytecode extraction determinism')
    parser.add_argument('test_file', nargs='?',
                        help='Run specific test file')
    
    args = parser.parse_args()
    
    if args.list:
        list_tests()
        return 0
    
    if args.test_file:
        # Run specific test
        test_file = Path(args.test_file)
        if not test_file.exists():
            print(f"Error: Test file not found: {test_file}")
            return 1
        
        if args.deterministic_check:
            consistent, message, total_ops1, total_ops2 = test_deterministic(test_file)
            print(f"Test: {test_file.name}")
            print(f"  First run:  {total_ops1} operations")
            print(f"  Second run: {total_ops2} operations")
            print(f"  Status: {message}")
            return 0 if consistent else 1
        else:
            passed, message, total_ops = run_test(test_file, generate=args.generate)
            print(f"Test: {test_file.name}")
            print(f"  Operations count: {total_ops}")
            print(f"  Status: {'PASS' if passed else 'FAIL'}")
            if not passed:
                print(f"  Message: {message}")
            return 0 if passed else 1
    
    # Run all tests
    success = run_all_tests(generate=args.generate, deterministic_check=args.deterministic_check)
    return 0 if success else 1


if __name__ == '__main__':
    sys.exit(main())
